FROM golang:1.23-alpine AS builder

RUN apk add --no-cache gcc musl-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev mesa-dev

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=1 GOOS=linux go build -o peer ./cmd/peer

FROM alpine:3.19
RUN apk --no-cache add ca-certificates libx11 mesa-gl ttf-dejavu
WORKDIR /app
COPY --from=builder /app/peer .

EXPOSE 9000
CMD ["./peer", "-stun", "http://stun:8080"]
